import type { Country } from "./type";

export const countries: Country[] = [
  { code: "+93", country: "Afghanistan", flag: "flags/af.svg" },
  { code: "+355", country: "Albania", flag: "flags/al.svg" },
  { code: "+213", country: "Algeria", flag: "flags/dz.svg" },
  { code: "+1", country: "American Samoa", flag: "flags/as.svg" },
  { code: "+376", country: "Andorra", flag: "flags/ad.svg" },
  { code: "+244", country: "Angola", flag: "flags/ao.svg" },
  { code: "+1", country: "Anguilla", flag: "flags/ai.svg" },
  { code: "+672", country: "Antarctica", flag: "flags/aq.svg" },
  {
    code: "+1",
    country: "Antigua and Barbuda",
    flag: "flags/ag.svg",
  },
  { code: "+54", country: "Argentina", flag: "flags/ar.svg" },
  { code: "+374", country: "Armenia", flag: "flags/am.svg" },
  { code: "+297", country: "Aruba", flag: "flags/aw.svg" },
  { code: "+61", country: "Australia", flag: "flags/au.svg" },
  { code: "+43", country: "Austria", flag: "flags/at.svg" },
  { code: "+994", country: "Azerbaijan", flag: "flags/az.svg" },
  { code: "+1", country: "Bahamas", flag: "flags/bs.svg" },
  { code: "+973", country: "Bahrain", flag: "flags/bh.svg" },
  { code: "+880", country: "Bangladesh", flag: "flags/bd.svg" },
  { code: "+1", country: "Barbados", flag: "flags/bb.svg" },
  { code: "+375", country: "Belarus", flag: "flags/by.svg" },
  { code: "+32", country: "Belgium", flag: "flags/be.svg" },
  { code: "+501", country: "Belize", flag: "flags/bz.svg" },
  { code: "+229", country: "Benin", flag: "flags/bj.svg" },
  { code: "+1", country: "Bermuda", flag: "flags/bm.svg" },
  { code: "+975", country: "Bhutan", flag: "flags/bt.svg" },
  { code: "+591", country: "Bolivia", flag: "flags/bo.svg" },
  {
    code: "+387",
    country: "Bosnia and Herzegovina",
    flag: "flags/ba.svg",
  },
  { code: "+267", country: "Botswana", flag: "flags/bw.svg" },
  { code: "+55", country: "Brazil", flag: "flags/br.svg" },
  {
    code: "+246",
    country: "British Indian Ocean Territory",
    flag: "flags/io.svg",
  },
  {
    code: "+1",
    country: "British Virgin Islands",
    flag: "flags/vg.svg",
  },
  { code: "+673", country: "Brunei", flag: "flags/bn.svg" },
  { code: "+359", country: "Bulgaria", flag: "flags/bg.svg" },
  { code: "+226", country: "Burkina Faso", flag: "flags/bf.svg" },
  { code: "+257", country: "Burundi", flag: "flags/bi.svg" },
  { code: "+855", country: "Cambodia", flag: "flags/kh.svg" },
  { code: "+237", country: "Cameroon", flag: "flags/cm.svg" },
  { code: "+1", country: "Canada", flag: "flags/ca.svg" },
  { code: "+238", country: "Cape Verde", flag: "flags/cv.svg" },
  { code: "+1", country: "Cayman Islands", flag: "flags/ky.svg" },
  {
    code: "+236",
    country: "Central African Republic",
    flag: "flags/cf.svg",
  },
  { code: "+235", country: "Chad", flag: "flags/td.svg" },
  { code: "+56", country: "Chile", flag: "flags/cl.svg" },
  { code: "+86", country: "China", flag: "flags/cn.svg" },
  { code: "+61", country: "Christmas Island", flag: "flags/cx.svg" },
  { code: "+61", country: "Cocos Islands", flag: "flags/cc.svg" },
  { code: "+57", country: "Colombia", flag: "flags/co.svg" },
  { code: "+269", country: "Comoros", flag: "flags/km.svg" },
  { code: "+682", country: "Cook Islands", flag: "flags/ck.svg" },
  { code: "+506", country: "Costa Rica", flag: "flags/cr.svg" },
  { code: "+385", country: "Croatia", flag: "flags/hr.svg" },
  { code: "+53", country: "Cuba", flag: "flags/cu.svg" },
  { code: "+599", country: "Curacao", flag: "flags/cw.svg" },
  { code: "+357", country: "Cyprus", flag: "flags/cy.svg" },
  { code: "+420", country: "Czech Republic", flag: "flags/cz.svg" },
  {
    code: "+243",
    country: "Democratic Republic of the Congo",
    flag: "flags/cd.svg",
  },
  { code: "+45", country: "Denmark", flag: "flags/dk.svg" },
  { code: "+253", country: "Djibouti", flag: "flags/dj.svg" },
  { code: "+1", country: "Dominica", flag: "flags/dm.svg" },
  { code: "+1", country: "Dominican Republic", flag: "flags/do.svg" },
  { code: "+670", country: "East Timor", flag: "flags/tl.svg" },
  { code: "+593", country: "Ecuador", flag: "flags/ec.svg" },
  { code: "+20", country: "Egypt", flag: "flags/eg.svg" },
  { code: "+503", country: "El Salvador", flag: "flags/sv.svg" },
  { code: "+240", country: "Equatorial Guinea", flag: "flags/gq.svg" },
  { code: "+291", country: "Eritrea", flag: "flags/er.svg" },
  { code: "+372", country: "Estonia", flag: "flags/ee.svg" },
  { code: "+268", country: "Eswatini", flag: "flags/sz.svg" },
  { code: "+251", country: "Ethiopia", flag: "flags/et.svg" },
  { code: "+500", country: "Falkland Islands", flag: "flags/fk.svg" },
  { code: "+298", country: "Faroe Islands", flag: "flags/fo.svg" },
  { code: "+679", country: "Fiji", flag: "flags/fj.svg" },
  { code: "+358", country: "Finland", flag: "flags/fi.svg" },
  { code: "+33", country: "France", flag: "flags/fr.svg" },
  { code: "+689", country: "French Polynesia", flag: "flags/pf.svg" },
  { code: "+241", country: "Gabon", flag: "flags/ga.svg" },
  { code: "+220", country: "Gambia", flag: "flags/gm.svg" },
  { code: "+995", country: "Georgia", flag: "flags/ge.svg" },
  { code: "+49", country: "Germany", flag: "flags/de.svg" },
  { code: "+233", country: "Ghana", flag: "flags/gh.svg" },
  { code: "+350", country: "Gibraltar", flag: "flags/gi.svg" },
  { code: "+30", country: "Greece", flag: "flags/gr.svg" },
  { code: "+299", country: "Greenland", flag: "flags/gl.svg" },
  { code: "+1", country: "Grenada", flag: "flags/gd.svg" },
  { code: "+1", country: "Guam", flag: "flags/gu.svg" },
  { code: "+502", country: "Guatemala", flag: "flags/gt.svg" },
  { code: "+44", country: "Guernsey", flag: "flags/gg.svg" },
  { code: "+224", country: "Guinea", flag: "flags/gn.svg" },
  { code: "+245", country: "Guinea-Bissau", flag: "flags/gw.svg" },
  { code: "+592", country: "Guyana", flag: "flags/gy.svg" },
  { code: "+509", country: "Haiti", flag: "flags/ht.svg" },
  { code: "+504", country: "Honduras", flag: "flags/hn.svg" },
  { code: "+852", country: "Hong Kong", flag: "flags/hk.svg" },
  { code: "+36", country: "Hungary", flag: "flags/hu.svg" },
  { code: "+354", country: "Iceland", flag: "flags/is.svg" },
  { code: "+91", country: "India", flag: "flags/in.svg" },
  { code: "+62", country: "Indonesia", flag: "flags/id.svg" },
  { code: "+98", country: "Iran", flag: "flags/ir.svg" },
  { code: "+964", country: "Iraq", flag: "flags/iq.svg" },
  { code: "+353", country: "Ireland", flag: "flags/ie.svg" },
  { code: "+44", country: "Isle of Man", flag: "flags/im.svg" },
  { code: "+972", country: "Israel", flag: "flags/il.svg" },
  { code: "+39", country: "Italy", flag: "flags/it.svg" },
  { code: "+225", country: "Ivory Coast", flag: "flags/ci.svg" },
  { code: "+1", country: "Jamaica", flag: "flags/jm.svg" },
  { code: "+81", country: "Japan", flag: "flags/jp.svg" },
  { code: "+44", country: "Jersey", flag: "flags/je.svg" },
  { code: "+962", country: "Jordan", flag: "flags/jo.svg" },
  { code: "+7", country: "Kazakhstan", flag: "flags/kz.svg" },
  { code: "+254", country: "Kenya", flag: "flags/ke.svg" },
  { code: "+686", country: "Kiribati", flag: "flags/ki.svg" },
  { code: "+383", country: "Kosovo", flag: "flags/xk.svg" },
  { code: "+965", country: "Kuwait", flag: "flags/kw.svg" },
  { code: "+996", country: "Kyrgyzstan", flag: "flags/kg.svg" },
  { code: "+856", country: "Laos", flag: "flags/la.svg" },
  { code: "+371", country: "Latvia", flag: "flags/lv.svg" },
  { code: "+961", country: "Lebanon", flag: "flags/lb.svg" },
  { code: "+266", country: "Lesotho", flag: "flags/ls.svg" },
  { code: "+231", country: "Liberia", flag: "flags/lr.svg" },
  { code: "+218", country: "Libya", flag: "flags/ly.svg" },
  { code: "+423", country: "Liechtenstein", flag: "flags/li.svg" },
  { code: "+370", country: "Lithuania", flag: "flags/lt.svg" },
  { code: "+352", country: "Luxembourg", flag: "flags/lu.svg" },
  { code: "+853", country: "Macao", flag: "flags/mo.svg" },
  { code: "+389", country: "Macedonia", flag: "flags/mk.svg" },
  { code: "+261", country: "Madagascar", flag: "flags/mg.svg" },
  { code: "+265", country: "Malawi", flag: "flags/mw.svg" },
  { code: "+60", country: "Malaysia", flag: "flags/my.svg" },
  { code: "+960", country: "Maldives", flag: "flags/mv.svg" },
  { code: "+223", country: "Mali", flag: "flags/ml.svg" },
  { code: "+356", country: "Malta", flag: "flags/mt.svg" },
  { code: "+692", country: "Marshall Islands", flag: "flags/mh.svg" },
  { code: "+222", country: "Mauritania", flag: "flags/mr.svg" },
  { code: "+230", country: "Mauritius", flag: "flags/mu.svg" },
  { code: "+262", country: "Mayotte", flag: "flags/yt.svg" },
  { code: "+52", country: "Mexico", flag: "flags/mx.svg" },
  { code: "+691", country: "Micronesia", flag: "flags/fm.svg" },
  { code: "+373", country: "Moldova", flag: "flags/md.svg" },
  { code: "+377", country: "Monaco", flag: "flags/mc.svg" },
  { code: "+976", country: "Mongolia", flag: "flags/mn.svg" },
  { code: "+382", country: "Montenegro", flag: "flags/me.svg" },
  { code: "+1", country: "Montserrat", flag: "flags/ms.svg" },
  { code: "+212", country: "Morocco", flag: "flags/ma.svg" },
  { code: "+258", country: "Mozambique", flag: "flags/mz.svg" },
  { code: "+95", country: "Myanmar", flag: "flags/mm.svg" },
  { code: "+264", country: "Namibia", flag: "flags/na.svg" },
  { code: "+674", country: "Nauru", flag: "flags/nr.svg" },
  { code: "+977", country: "Nepal", flag: "flags/np.svg" },
  { code: "+31", country: "Netherlands", flag: "flags/nl.svg" },
  {
    code: "+599",
    country: "Netherlands Antilles",
    flag: "flags/bq.svg",
  },
  { code: "+687", country: "New Caledonia", flag: "flags/nc.svg" },
  { code: "+64", country: "New Zealand", flag: "flags/nz.svg" },
  { code: "+505", country: "Nicaragua", flag: "flags/ni.svg" },
  { code: "+227", country: "Niger", flag: "flags/ne.svg" },
  { code: "+234", country: "Nigeria", flag: "flags/ng.svg" },
  { code: "+683", country: "Niue", flag: "flags/nu.svg" },
  { code: "+850", country: "North Korea", flag: "flags/kp.svg" },
  {
    code: "+1",
    country: "Northern Mariana Islands",
    flag: "flags/mp.svg",
  },
  { code: "+47", country: "Norway", flag: "flags/no.svg" },
  { code: "+968", country: "Oman", flag: "flags/om.svg" },
  { code: "+92", country: "Pakistan", flag: "flags/pk.svg" },
  { code: "+680", country: "Palau", flag: "flags/pw.svg" },
  { code: "+970", country: "Palestine", flag: "flags/ps.svg" },
  { code: "+507", country: "Panama", flag: "flags/pa.svg" },
  { code: "+675", country: "Papua New Guinea", flag: "flags/pg.svg" },
  { code: "+595", country: "Paraguay", flag: "flags/py.svg" },
  { code: "+51", country: "Peru", flag: "flags/pe.svg" },
  { code: "+63", country: "Philippines", flag: "flags/ph.svg" },
  { code: "+64", country: "Pitcairn", flag: "flags/pn.svg" },
  { code: "+48", country: "Poland", flag: "flags/pl.svg" },
  { code: "+351", country: "Portugal", flag: "flags/pt.svg" },
  { code: "+1", country: "Puerto Rico", flag: "flags/pr.svg" },
  { code: "+974", country: "Qatar", flag: "flags/qa.svg" },
  {
    code: "+242",
    country: "Republic of the Congo",
    flag: "flags/cg.svg",
  },
  { code: "+262", country: "Reunion", flag: "flags/re.svg" },
  { code: "+40", country: "Romania", flag: "flags/ro.svg" },
  { code: "+7", country: "Russia", flag: "flags/ru.svg" },
  { code: "+250", country: "Rwanda", flag: "flags/rw.svg" },
  { code: "+590", country: "Saint Barthelemy", flag: "flags/bl.svg" },
  { code: "+290", country: "Saint Helena", flag: "flags/sh.svg" },
  {
    code: "+1",
    country: "Saint Kitts and Nevis",
    flag: "flags/kn.svg",
  },
  { code: "+1", country: "Saint Lucia", flag: "flags/lc.svg" },
  { code: "+590", country: "Saint Martin", flag: "flags/mf.svg" },
  {
    code: "+508",
    country: "Saint Pierre and Miquelon",
    flag: "flags/pm.svg",
  },
  {
    code: "+1",
    country: "Saint Vincent and the Grenadines",
    flag: "flags/vc.svg",
  },
  { code: "+685", country: "Samoa", flag: "flags/ws.svg" },
  { code: "+378", country: "San Marino", flag: "flags/sm.svg" },
  {
    code: "+239",
    country: "Sao Tome and Principe",
    flag: "flags/st.svg",
  },
  { code: "+966", country: "Saudi Arabia", flag: "flags/sa.svg" },
  { code: "+221", country: "Senegal", flag: "flags/sn.svg" },
  { code: "+381", country: "Serbia", flag: "flags/rs.svg" },
  { code: "+248", country: "Seychelles", flag: "flags/sc.svg" },
  { code: "+232", country: "Sierra Leone", flag: "flags/sl.svg" },
  { code: "+65", country: "Singapore", flag: "flags/sg.svg" },
  { code: "+1", country: "Sint Maarten", flag: "flags/sx.svg" },
  { code: "+421", country: "Slovakia", flag: "flags/sk.svg" },
  { code: "+386", country: "Slovenia", flag: "flags/si.svg" },
  { code: "+677", country: "Solomon Islands", flag: "flags/sb.svg" },
  { code: "+252", country: "Somalia", flag: "flags/so.svg" },
  { code: "+27", country: "South Africa", flag: "flags/za.svg" },
  { code: "+82", country: "South Korea", flag: "flags/kr.svg" },
  { code: "+211", country: "South Sudan", flag: "flags/ss.svg" },
  { code: "+34", country: "Spain", flag: "flags/es.svg" },
  { code: "+94", country: "Sri Lanka", flag: "flags/lk.svg" },
  { code: "+249", country: "Sudan", flag: "flags/sd.svg" },
  { code: "+597", country: "Suriname", flag: "flags/sr.svg" },
  {
    code: "+47",
    country: "Svalbard and Jan Mayen",
    flag: "flags/sj.svg",
  },
  { code: "+46", country: "Sweden", flag: "flags/se.svg" },
  { code: "+41", country: "Switzerland", flag: "flags/ch.svg" },
  { code: "+963", country: "Syria", flag: "flags/sy.svg" },
  { code: "+886", country: "Taiwan", flag: "flags/tw.svg" },
  { code: "+992", country: "Tajikistan", flag: "flags/tj.svg" },
  { code: "+255", country: "Tanzania", flag: "flags/tz.svg" },
  { code: "+66", country: "Thailand", flag: "flags/th.svg" },
  { code: "+228", country: "Togo", flag: "flags/tg.svg" },
  { code: "+690", country: "Tokelau", flag: "flags/tk.svg" },
  { code: "+676", country: "Tonga", flag: "flags/to.svg" },
  {
    code: "+1",
    country: "Trinidad and Tobago",
    flag: "flags/tt.svg",
  },
  { code: "+216", country: "Tunisia", flag: "flags/tn.svg" },
  { code: "+90", country: "Turkey", flag: "flags/tr.svg" },
  { code: "+993", country: "Turkmenistan", flag: "flags/tm.svg" },
  {
    code: "+1",
    country: "Turks and Caicos Islands",
    flag: "flags/tc.svg",
  },
  { code: "+688", country: "Tuvalu", flag: "flags/tv.svg" },
  {
    code: "+1",
    country: "U.S. Virgin Islands",
    flag: "flags/vi.svg",
  },
  { code: "+256", country: "Uganda", flag: "flags/ug.svg" },
  { code: "+380", country: "Ukraine", flag: "flags/ua.svg" },
  {
    code: "+971",
    country: "United Arab Emirates",
    flag: "flags/ae.svg",
  },
  { code: "+44", country: "United Kingdom", flag: "flags/gb.svg" },
  { code: "+1", country: "United States", flag: "flags/us.svg" },
  { code: "+598", country: "Uruguay", flag: "flags/uy.svg" },
  { code: "+998", country: "Uzbekistan", flag: "flags/uz.svg" },
  { code: "+678", country: "Vanuatu", flag: "flags/vu.svg" },
  { code: "+379", country: "Vatican", flag: "flags/va.svg" },
  { code: "+58", country: "Venezuela", flag: "flags/ve.svg" },
  { code: "+84", country: "Vietnam", flag: "flags/vn.svg" },
  { code: "+681", country: "Wallis and Futuna", flag: "flags/wf.svg" },
  { code: "+212", country: "Western Sahara", flag: "flags/eh.svg" },
  { code: "+967", country: "Yemen", flag: "flags/ye.svg" },
  { code: "+260", country: "Zambia", flag: "flags/zm.svg" },
  { code: "+263", country: "Zimbabwe", flag: "flags/zw.svg" },
];
